#!/usr/bin/env python3
"""Extract KEY TAKEAWAYS + TEACHING SLIDES from /note-writer output → Marp .md for GitHub Pages.

Usage: python3 extract-slides.py <note.md> [--chapter 63] [--output slides/ch63-peritoneal-dialysis.md] [--textbook "Daugirdas Handbook of Dialysis 6e"]
If --output not given, auto-generates from chapter number and note title.
"""

import argparse, re, sys, os

DEFAULT_TEXTBOOK = "Brenner & Rector's The Kidney 12e"
SLIDE_HEADING_RE = re.compile(r'\n## (?:\d|Slide)')

MARP_TEMPLATE = """---
marp: true
theme: default
paginate: true
header: "TEXTBOOK_PLACEHOLDER"
footer: "FOOTER_PLACEHOLDER"
style: |
  section { font-size: 24px; }
  h1 { font-size: 36px; color: #1a5276; }
  h2 { font-size: 30px; color: #2c3e50; }
  li { font-size: 22px; line-height: 1.6; }
---
"""

def extract(note_path, chapter, output_path, textbook=None):
    with open(note_path, 'r') as f:
        content = f.read()

    # Extract title from frontmatter
    title_match = re.search(r'^title:\s*"?(.+?)"?\s*$', content, re.MULTILINE)
    title = title_match.group(1) if title_match else f"Chapter {chapter}"

    # Extract KEY TAKEAWAYS
    kt_match = re.search(r'## KEY TAKEAWAYS\n(.*?)(?=\n---|\n## (?!KEY))', content, re.DOTALL)
    takeaways = kt_match.group(1).strip() if kt_match else ""

    # Extract TEACHING SLIDES (everything after 本章結束 or ## TEACHING SLIDES)
    slides_section = ""
    end_marker = re.search(r'—— 本章結束 ——', content)
    if end_marker:
        after = content[end_marker.end():]
        # Find the slides content (starts with # Title or ## 01)
        slides_match = re.search(r'(#\s+.+\n(?:.*\n)*)', after)
        if slides_match:
            slides_section = slides_match.group(1).strip()

    if not slides_section:
        # Fallback: find ## TEACHING SLIDES directly
        ts_match = re.search(r'## TEACHING SLIDES\n(.*)', content, re.DOTALL)
        if ts_match:
            slides_section = ts_match.group(1).strip()

    if not takeaways and not slides_section:
        print("ERROR: Could not extract takeaways or slides from note", file=sys.stderr)
        sys.exit(1)

    # Build Marp .md
    footer = f"Ch.{chapter} — Generated by Claude Code"
    tb = textbook or DEFAULT_TEXTBOOK
    out = MARP_TEMPLATE.replace("FOOTER_PLACEHOLDER", footer).replace("TEXTBOOK_PLACEHOLDER", tb)

    # Title slide
    out += f"\n# {title}\n"
    out += f"### Brenner & Rector's The Kidney, 12th Edition — Chapter {chapter}\n"
    out += "#### Generated by Claude Code from teaching notes\n\n---\n\n"

    # Takeaways
    if takeaways:
        out += "# KEY TAKEAWAYS\n\n---\n\n"
        bullets = [b.strip() for b in takeaways.split('\n') if b.strip().startswith('-')]
        mid = len(bullets) // 2
        out += "## Key Takeaways (1/2)\n"
        for b in bullets[:mid]:
            out += f"{b}\n"
        out += "\n---\n\n"
        out += "## Key Takeaways (2/2)\n"
        for b in bullets[mid:]:
            out += f"{b}\n"
        out += "\n---\n\n"

    # Teaching slides
    if slides_section:
        out += "# TEACHING SLIDES\n\n---\n\n"
        # Split by ## headings (supports "## 01 Title", "## Slide 1: Title", "## Slide N Title")
        slide_blocks = re.split(r'\n(?=## (?:\d|Slide))', slides_section)
        for block in slide_blocks:
            block = block.strip()
            if block:
                out += block + "\n\n---\n\n"

    # Write
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(out)

    slide_count = len(re.findall(r'\n## (?:\d|Slide)', out))
    print(f"OK: {output_path} ({slide_count} slides)")
    return output_path, title, slide_count

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("note", help="Path to note.md")
    p.add_argument("--chapter", "-c", required=True, help="Chapter number")
    p.add_argument("--output", "-o", help="Output .md path")
    p.add_argument("--textbook", "-t", help="Textbook name for slide header")
    args = p.parse_args()

    if not args.output:
        args.output = f"slides/ch{args.chapter}.md"

    extract(args.note, args.chapter, args.output, args.textbook)
