#!/usr/bin/env python3
"""Watch nephrology textbook notes → extract slides → push to GitHub Pages.

Supports multiple books. Scans each book dir for note .md files,
extracts TEACHING SLIDES, pushes to textbook-notes repo.

Run via cron: */10 * * * * python3 brenner-slides-sync.py
"""

import os, sys, subprocess, re, glob

VAULT = "/Users/copper/VaultBinary"
SLIDES_REPO = os.path.join(VAULT, "repos/textbook-notes")
EXTRACT_SCRIPT = os.path.join(SLIDES_REPO, "extract-slides.py")

# Each book: (book_dir, note_glob_pattern, chapter_regex, slide_prefix)
BOOKS = [
    {
        "name": "Brenner & Rector 12e",
        "textbook_header": "Brenner & Rector's The Kidney 12e",
        "dir": os.path.join(VAULT, "raw/books/Brenner"),
        "note_pattern": "ch*/BrennerRector12e_*.md",
        "ch_extract": lambda path: re.search(r'ch(\d+)', path).group(1) if re.search(r'ch(\d+)', path) else None,
        "slide_prefix": "brenner",
    },
    {
        "name": "Daugirdas 6e",
        "textbook_header": "Daugirdas Handbook of Dialysis 6e",
        "dir": os.path.join(VAULT, "raw/books/2026_Daugirdas_6e"),
        "note_pattern": "Ch*.md",
        "ch_extract": lambda path: re.search(r'Ch(\d+)', os.path.basename(path)).group(1) if re.search(r'Ch(\d+)', os.path.basename(path)) else None,
        "slide_prefix": "daugirdas",
    },
]

def slug(note_path, prefix):
    base = os.path.basename(note_path).replace(".md", "")
    # Remove leading Ch01_ or BrennerRector12e_Ch63_ etc
    base = re.sub(r'^(BrennerRector12e_|Ch\d+_)', '', base)
    # CamelCase → kebab
    parts = re.findall(r'[A-Z\u4e00-\u9fff][a-z\u4e00-\u9fff]*|[A-Z]+(?=[A-Z]|$)|\d+|[_]', base)
    kebab = "-".join(p.lower().strip("_") for p in parts if p.strip("_"))
    return kebab if kebab else "untitled"

def needs_update(note_path, slide_path):
    if not os.path.exists(slide_path):
        return True
    return os.path.getmtime(note_path) > os.path.getmtime(slide_path)

def update_index(all_notes_info):
    """Regenerate index.md grouped by book."""
    sections = []
    for book_name, notes in sorted(all_notes_info.items()):
        rows = []
        for ch, title, slide_count, html_name in sorted(notes, key=lambda x: int(x[0]) if x[0].isdigit() else 0):
            rows.append(f"| {ch} | [{title}](slides/{html_name}) | {slide_count} slides |")
        section = f"### {book_name}\n\n| Ch | Title | Slides |\n|---|---|---|\n" + "\n".join(rows)
        sections.append(section)

    index = """---
marp: false
---

# 腎臟專科考試複習 — Teaching Slides
## Nephrology Board Review

""" + "\n\n".join(sections) + """

---
*Teaching notes generated by Claude Code. Not original textbook content.*
"""
    with open(os.path.join(SLIDES_REPO, "index.md"), "w") as f:
        f.write(index)

def main():
    changed = False
    all_notes_info = {}

    for book in BOOKS:
        book_name = book["name"]
        notes_info = []
        pattern = os.path.join(book["dir"], book["note_pattern"])

        for note_path in sorted(glob.glob(pattern)):
            ch = book["ch_extract"](note_path)
            if not ch:
                continue

            s = slug(note_path, book["slide_prefix"])
            slide_filename = f"{book['slide_prefix']}-ch{ch}-{s}.md"
            slide_path = os.path.join(SLIDES_REPO, "slides", slide_filename)

            if needs_update(note_path, slide_path):
                print(f"[{book_name}] Extracting ch{ch}: {os.path.basename(note_path)}")
                result = subprocess.run(
                    ["python3", EXTRACT_SCRIPT, note_path, "-c", ch, "-o", slide_path,
                     "-t", book.get("textbook_header", book["name"])],
                    capture_output=True, text=True
                )
                if result.returncode != 0:
                    err = result.stderr[:200]
                    if "Could not extract takeaways or slides from note" in err:
                        # Legacy / non-v2.6 format — expected skip, not an error
                        print(f"  SKIP: {os.path.basename(note_path)} (legacy format, no v2.6 markers)", file=sys.stderr)
                    else:
                        print(f"  ERROR: {err}", file=sys.stderr)
                    continue
                print(f"  {result.stdout.strip()}")
                changed = True

            if os.path.exists(slide_path):
                with open(slide_path) as f:
                    content = f.read()
                slide_count = len(re.findall(r'\n## (?:\d|Slide)', content))
                title_match = re.search(r'^# (.+)$', content, re.MULTILINE)
                title = title_match.group(1) if title_match else f"Chapter {ch}"
                html_name = os.path.basename(slide_path).replace(".md", ".html")
                notes_info.append((ch, title, slide_count, html_name))

        if notes_info:
            all_notes_info[book_name] = notes_info

    if changed and all_notes_info:
        update_index(all_notes_info)
        os.chdir(SLIDES_REPO)
        subprocess.run(["git", "add", "-A"], capture_output=True)
        result = subprocess.run(["git", "diff", "--cached", "--quiet"], capture_output=True)
        if result.returncode != 0:
            subprocess.run(["git", "commit", "-m", "auto: slides sync"], capture_output=True)
            push = subprocess.run(["git", "push"], capture_output=True, text=True)
            if push.returncode == 0:
                print("Pushed → Pages will rebuild")
            else:
                print(f"Push failed: {push.stderr[:200]}", file=sys.stderr)

if __name__ == "__main__":
    main()
